const app = new Vue({
	el: '#app',
	data: {
	items:[
	{titulo:'Care Plan'},
	{titulo:'Care Plan Name'},
	{titulo:'Care plan Need Identified'},
	{titulo:'Care Plan Commenced'},
	{titulo:'Care Plan Developed'},
	{titulo:'Care Plan Expired'},
	{titulo:'Care Plan Completed'},
	{titulo:'Tree'},
	{titulo:'Care Plan ID'},
	{titulo:'Expiry Date'},
	{titulo:'Care Plan Scheduled'},
	{titulo:'Tree'},
	{titulo:'Care Plan Reviewed'},
	{titulo:'Description'},
	{titulo:'Reason'},
	{titulo:'Care Plan Aborted'},
	{titulo:'Care Plan Cancelled'},
	{titulo:'Care Plan Postponed'},
	{titulo:'Care Plan Suspended'},
	{titulo:'Health education'},
	{titulo:'Tree'},
	{titulo:'Topic name'},
	{titulo:'Description'},
	{titulo:'Method'},
	{titulo:'Education planned'},
	{titulo:'Education scheduled'},
	{titulo:'Education provided'},
	{titulo:'Reason'},
	{titulo:'Education completed'},
	{titulo:'Education postponed'},
	{titulo:'Education cancelled'},
	{titulo:'Education not completed'},
	{titulo:'Education suspended'},
	{titulo:'Education recommended'},
	{titulo:'Outcome'},
	{titulo:'Session Number'},
	{titulo:'Tree'},
	{titulo:'Extension'},
	{titulo:'Material details'},
	{titulo:'Scheduled date/ time'},
	{titulo:'Comment'},
	{titulo:'Requestor'},
	{titulo:'Receiver'},
	{titulo:'Requestor order identifier'},
	{titulo:'Receiver order identifier'},
	{titulo:'Recipient'},
	{titulo:'Additional details'},
	{titulo:'Interpreter details'},
	{titulo:'Imaging examination'},
	{titulo:'Tree'},
	{titulo:'Examination planned'},
	{titulo:'Examination requested'},
	{titulo:'Appointment scheduled'},
	{titulo:'Appointment rescheduled'},
	{titulo:'Examination complete'},
	{titulo:'Examination performed'},
	{titulo:'Examination postponed'},
	{titulo:'Examination suspended'},
	{titulo:'Examination cancelled'},
	{titulo:'Examination aborted'},
	{titulo:'Failed attempt'},
	{titulo:'Tree'},
	{titulo:'Start date/time'},
	{titulo:'Examination name'},
	{titulo:'Description'},
	{titulo:'Reason'},
	{titulo:'Comment'},
	{titulo:'Examination detail'},
	{titulo:'Anatomical location'},
	{titulo:'Informed Consent'},
	{titulo:'Tree'},
	{titulo:'Procedure/Trial/Activity'},
	{titulo:'Details'},
	{titulo:'Form of Consent'},
	{titulo:'Written'},
	{titulo:'Verbal'},
	{titulo:'Reason'},
	{titulo:'Start Date'},
	{titulo:'End Date'},
	{titulo:'Caveat'},
	{titulo:'Consent Description'},
	{titulo:'Evidence of Consent'},
	{titulo:'Planned'},
	{titulo:'Informed Consent Requested'},
	{titulo:'Informed Consent Provided'},
	{titulo:'Informed Consent Refused'},
	{titulo:'Informed Consent Withdrawn'},
	{titulo:'Cancelled'},
	{titulo:'Postponed'},
	{titulo:'Informed Consent Not Obtained'},
	{titulo:'Completed'},
	{titulo:'Tree'},
	{titulo:'Consent Document Used'},
	{titulo:'Review Date'},
	{titulo:'Appointment Scheduled'},
	{titulo:'Consent Requester'},
	{titulo:'Consent Provider'},
	{titulo:'Procedure/Trial/Activity Description'},
	{titulo:'Intent'},
	{titulo:'Name'},
	{titulo:'Patient Information'},
	{titulo:'Multimedia Representation'},
	{titulo:'Description'},
	{titulo:'Medication management'},
	{titulo:'Prescription issued'},
	{titulo:'Prescription dispensed'},
	{titulo:'Medication course commenced'},
	{titulo:'Medication reassessed'},
	{titulo:'Dose administered'},
	{titulo:'Medication course completed'},
	{titulo:'Prescription supply delayed'},
	{titulo:'Administrations suspended'},
	{titulo:'Prescription re-issued'},
	{titulo:'Prescription re-authorisation pending'},
	{titulo:'Medication course cancelled'},
	{titulo:'Medication course postponed'},
	{titulo:'Medication course stopped'},
	{titulo:'Medication start date/condition set'},
	{titulo:'Tree'},
	{titulo:'Dose administration omitted'},
	{titulo:'Medication item'},
	{titulo:'Reason'},
	{titulo:'Comment'},
	{titulo:'Sequence number'},
	{titulo:'Tree'},
	{titulo:'Patient guidance'},
	{titulo:'Major change to order'},
	{titulo:'Minor change to order'},
	{titulo:'Original scheduled date/time'},
	{titulo:'Dose administration deferred'},
	{titulo:'Additional details'},
	{titulo:'Extension'},
	{titulo:'Order ID'},
	{titulo:'Medication details'},
	{titulo:'Prescription re-authorised'},
	{titulo:'Medication recommended'},
	{titulo:'Amount'},
	{titulo:'Substitution'},
	{titulo:'Substitution reason'},
	{titulo:'Substitution performed'},
	{titulo:'Substitution not performed'},
	{titulo:'Administration details'},
	{titulo:'Body site'},
	{titulo:'Structured body site'},
	{titulo:'Administration method'},
	{titulo:'Administration device'},
	{titulo:'Prescription awaiting authorisation'},
	{titulo:'Route'},
	{titulo:'Medication prepared'},
	{titulo:'Double-checked?'},
	{titulo:'Prescription cancelled'},
	{titulo:'Prescription invalid or expired'},
	{titulo:'Prescription fulfilled'},
	{titulo:'Medication authorised'},
	{titulo:'Restart date/time'},
	{titulo:'Restart criterion'},
	{titulo:'Notification'},
	{titulo:'Tree'},
	{titulo:'Addressee'},
	{titulo:'Type'},
	{titulo:'Reason'},
	{titulo:'Method'},
	{titulo:'Date sent'},
	{titulo:'Comment'},
	{titulo:'Need identified'},
	{titulo:'Dictated'},
	{titulo:'Created'},
	{titulo:'Signed'},
	{titulo:'Sent'},
	{titulo:'Tree'},
	{titulo:'Extension'},
	{titulo:'Osteosynthesis after fracture'},
	{titulo:'Arthrodesis'},
	{titulo:'Osteotomy of Femur'},
	{titulo:'Osteotomy of Acetabulum'},
	{titulo:'Procedure undertaken'},
	{titulo:'Primary hip arthroplasty - previous procedure'},
	{titulo:'Tree'},
	{titulo:'Procedure'},
	{titulo:'Previous procedure'},
	{titulo:'Procedure Details'},
	{titulo:'Procedure unsuccessful'},
	{titulo:'Comments'},
	{titulo:'Complication'},
	{titulo:'Multimedia'},
	{titulo:'Reason/s for procedure'},
	{titulo:'Unplanned event'},
	{titulo:'Failed attempts'},
	{titulo:'Additional tasks'},
	{titulo:'Task description'},
	{titulo:'Record of additional task'},
	{titulo:'Request initiated'},
	{titulo:'Request sent'},
	{titulo:'Procedure scheduled'},
	{titulo:'Request postponed'},
	{titulo:'Request cancelled'},
	{titulo:'Procedure suspended'},
	{titulo:'Procedure aborted'},
	{titulo:'Completed'},
	{titulo:'Report authored'},
	{titulo:'Report attested'},
	{titulo:'Report sent'},
	{titulo:'In progress'},
	{titulo:'Outcome'},
	{titulo:'Description'},
	{titulo:'Anatomical site details'},
	{titulo:'Method/Technique'},
	{titulo:'Task'},
	{titulo:'Tree'},
	{titulo:'Requestor order identifier'},
	{titulo:'Requestor'},
	{titulo:'Receiver order identifier'},
	{titulo:'Receiver'},
	{titulo:'Emergency?'},
	{titulo:'Partial hip arthroplasty'},
	{titulo:'Primary Total Standard hip arthroplasty'},
	{titulo:'Replacement of whole system'},
	{titulo:'Replacement of Acetabular component'},
	{titulo:'Replacement of Femoral component'},
	{titulo:'Replacement of Head'},
	{titulo:'Replacement of Inlay'},
	{titulo:'Prosthesis removal (Girdlestone)'},
	{titulo:'Primary Total Resurfacing hip arthroplasty'},
	{titulo:'Primary Partial Bipolar Hip arthroplasty'},
	{titulo:'Primary Partial Resurfacing hip arthroplasty'},
	{titulo:'Replacement of bipolar/partial implant'},
	{titulo:'Re-implantation after Girdlestone'},
	{titulo:'Replacement of Acetabular ring'},
	{titulo:'Replacement of Neck'},
	{titulo:'Procedure undertaken'},
	{titulo:'Revision hip arthroplasty- previous procedure'},
	{titulo:'Tree'},
	{titulo:'Procedure'},
	{titulo:'Previous procedure'},
	{titulo:'Procedure Details'},
	{titulo:'Procedure unsuccessful'},
	{titulo:'Comments'},
	{titulo:'Complication'},
	{titulo:'Multimedia'},
	{titulo:'Reason/s for procedure'},
	{titulo:'Unplanned event'},
	{titulo:'Failed attempts'},
	{titulo:'Additional tasks'},
	{titulo:'Task description'},
	{titulo:'Record of additional task'},
	{titulo:'Request initiated'},
	{titulo:'Request sent'},
	{titulo:'Procedure scheduled'},
	{titulo:'Request postponed'},
	{titulo:'Request cancelled'},
	{titulo:'Procedure suspended'},
	{titulo:'Procedure aborted'},
	{titulo:'Completed'},
	{titulo:'Report authored'},
	{titulo:'Report attested'},
	{titulo:'Report sent'},
	{titulo:'In progress'},
	{titulo:'Outcome'},
	{titulo:'Description'},
	{titulo:'Anatomical site details'},
	{titulo:'Method/Technique'},
	{titulo:'Task'},
	{titulo:'Tree'},
	{titulo:'Requestor order identifier'},
	{titulo:'Requestor'},
	{titulo:'Receiver order identifier'},
	{titulo:'Receiver'},
	{titulo:'Emergency?'},
	{titulo:'Total standard hip replacement'},
	{titulo:'Partial bipolar hip replacement'},
	{titulo:'Partial resurfacing hip replacement'},
	{titulo:'Primary Osteoarthritis'},
	{titulo:'Dysplasia /dysplasia with dislocation'},
	{titulo:'Post-Traumatic'},
	{titulo:'Aseptic Necrosis of Femoral Head'},
	{titulo:'Post epipholysis / post Perthes'},
	{titulo:'Rheumatoid Arthritis, other arthritis and anylosing spondyilitis'},
	{titulo:'Cemented'},
	{titulo:'Uncemented'},
	{titulo:'Hybrid-cemented stem only'},
	{titulo:'Inverse_ Hybrid'},
	{titulo:'Anterior,'},
	{titulo:'Anterolateral, Direct_lateral,'},
	{titulo:'Posterolateral, Minimal_Invasive'},
	{titulo:'Anterior'},
	{titulo:'Anterolateral'},
	{titulo:'Direct lateral'},
	{titulo:'Posterolateral'},
	{titulo:'Minimally Invasive'},
	{titulo:'Other'},
	{titulo:'Total resurfacing hip replacement'},
	{titulo:'Procedure undertaken'},
	{titulo:'Primary hip arthroplasty'},
	{titulo:'Tree'},
	{titulo:'Procedure'},
	{titulo:'Current procedure'},
	{titulo:'Procedure Details'},
	{titulo:'Procedure unsuccessful'},
	{titulo:'Comments'},
	{titulo:'Complication'},
	{titulo:'Multimedia'},
	{titulo:'Reason/s for procedure'},
	{titulo:'Reason for procedure'},
	{titulo:'Unplanned event'},
	{titulo:'Failed attempts'},
	{titulo:'Additional tasks'},
	{titulo:'Task description'},
	{titulo:'Record of additional task'},
	{titulo:'Request initiated'},
	{titulo:'Request sent'},
	{titulo:'Procedure scheduled'},
	{titulo:'Request postponed'},
	{titulo:'Request cancelled'},
	{titulo:'Procedure suspended'},
	{titulo:'Procedure aborted'},
	{titulo:'Completed'},
	{titulo:'Report authored'},
	{titulo:'Report attested'},
	{titulo:'Report sent'},
	{titulo:'In progress'},
	{titulo:'Outcome'},
	{titulo:'Description'},
	{titulo:'Anatomical site details'},
	{titulo:'Method/Technique'},
	{titulo:'Prosthesis fixation'},
	{titulo:'Approach'},
	{titulo:'Task'},
	{titulo:'Tree'},
	{titulo:'Requestor order identifier'},
	{titulo:'Requestor'},
	{titulo:'Receiver order identifier'},
	{titulo:'Receiver'},
	{titulo:'Emergency?'},
	{titulo:'Anterolateral'},
	{titulo:'Direct lateral'},
	{titulo:'Posterolateral'},
	{titulo:'Minimally Invasive'},
	{titulo:'Cemented'},
	{titulo:'Uncemented'},
	{titulo:'Hybrid-cemented stem only'},
	{titulo:'Inverse_ Hybrid'},
	{titulo:'Replacement of femoral neck'},
	{titulo:'Osteotomy of femur'},
	{titulo:'Osteotomy of acetabulum'},
	{titulo:'Athrodesis'},
	{titulo:'Extended anterior approach'},
	{titulo:'Osteolysis both parts'},
	{titulo:'Replacement of acetabular ring'},
	{titulo:'Replacement of neck'},
	{titulo:'Replacement of whole system'},
	{titulo:'Replacement of acetabular component'},
	{titulo:'Replacement of femoral component'},
	{titulo:'Replacement of head'},
	{titulo:'Replacement of Inlay'},
	{titulo:'Totalisation of bipolar/partial Implant'},
	{titulo:'Osteosynthesis after fracture'},
	{titulo:'Prosthesis removal (Girdlestone)'},
	{titulo:'Re-implantation after Girdlestone'},
	{titulo:'Para-articular ossification'},
	{titulo:'Luxation'},
	{titulo:'Wear'},
	{titulo:'Early infection'},
	{titulo:'Chronic infection'},
	{titulo:'Metal/taper related pathology'},
	{titulo:'Loosening acetabular component'},
	{titulo:'Loosening femoral component'},
	{titulo:'Osteolysis acetabulum'},
	{titulo:'Osteolysis femur'},
	{titulo:'Large bone defect acetabulum'},
	{titulo:'Large bone defect femur (distal minor trochanter)'},
	{titulo:'Periprosthetic fracture'},
	{titulo:'Implant broken'},
	{titulo:'Loosening acetabular component'},
	{titulo:'Loosening femoral component'},
	{titulo:'Loosening of both components'},
	{titulo:'Luxation'},
	{titulo:'Early infection (less than 3 months after primary)'},
	{titulo:'Chronic infection (more than 3 months after primary)'},
	{titulo:'Periprosthetic fracture of acetabulum'},
	{titulo:'Periprosthetic fracture of femur'},
	{titulo:'Osteolysis of acetabulum'},
	{titulo:'Osteolysis of femur'},
	{titulo:'Osteolysis of both parts'},
	{titulo:'Implant broken'},
	{titulo:'Wear of Inlay'},
	{titulo:'Paraarticular ossification'},
	{titulo:'Condition after Girdlestone'},
	{titulo:'Pain'},
	{titulo:'Others'},
	{titulo:'Anterior'},
	{titulo:'Procedure undertaken'},
	{titulo:'Revision hip arthroplasty'},
	{titulo:'Tree'},
	{titulo:'Procedure'},
	{titulo:'Revison procedure'},
	{titulo:'Procedure Details'},
	{titulo:'Procedure unsuccessful'},
	{titulo:'Comments'},
	{titulo:'Complication'},
	{titulo:'Multimedia'},
	{titulo:'Reason/s for procedure'},
	{titulo:'Reason/s for procedure'},
	{titulo:'Unplanned event'},
	{titulo:'Failed attempts'},
	{titulo:'Additional tasks'},
	{titulo:'Task description'},
	{titulo:'Record of additional task'},
	{titulo:'Request initiated'},
	{titulo:'Request sent'},
	{titulo:'Procedure scheduled'},
	{titulo:'Request postponed'},
	{titulo:'Request cancelled'},
	{titulo:'Procedure suspended'},
	{titulo:'Procedure aborted'},
	{titulo:'Completed'},
	{titulo:'Report authored'},
	{titulo:'Report attested'},
	{titulo:'Report sent'},
	{titulo:'In progress'},
	{titulo:'Outcome'},
	{titulo:'Description'},
	{titulo:'Anatomical site details'},
	{titulo:'Method/Technique'},
	{titulo:'Prosthesis fixation'},
	{titulo:'Approach'},
	{titulo:'Task'},
	{titulo:'Tree'},
	{titulo:'Requestor order identifier'},
	{titulo:'Requestor'},
	{titulo:'Receiver order identifier'},
	{titulo:'Receiver'},
	{titulo:'Emergency?'},
	{titulo:'Procedure'},
	{titulo:'Tree'},
	{titulo:'Procedure name'},
	{titulo:'Procedure detail'},
	{titulo:'Procedure planned'},
	{titulo:'Comment'},
	{titulo:'Complication'},
	{titulo:'Procedure request sent'},
	{titulo:'Reason'},
	{titulo:'X - Procedure planned'},
	{titulo:'X - Procedure request sent'},
	{titulo:'Procedure scheduled'},
	{titulo:'Procedure postponed'},
	{titulo:'Procedure cancelled'},
	{titulo:'Procedure suspended'},
	{titulo:'Procedure aborted'},
	{titulo:'Procedure completed'},
	{titulo:'Procedure performed'},
	{titulo:'Outcome'},
	{titulo:'Description'},
	{titulo:'Tree'},
	{titulo:'Requestor order identifier'},
	{titulo:'Requestor'},
	{titulo:'Receiver order identifier'},
	{titulo:'Receiver'},
	{titulo:'Urgency'},
	{titulo:'Final end date/time'},
	{titulo:'Total duration'},
	{titulo:'Multimedia'},
	{titulo:'Body site'},
	{titulo:'Extension'},
	{titulo:'Method'},
	{titulo:'Scheduled date/time'},
	{titulo:'Procedure type'},
	{titulo:'Procedure commenced'},
	{titulo:'Procedural difficulty'},
	{titulo:'Review'},
	{titulo:'Tree'},
	{titulo:'Review Activity'},
	{titulo:'Review Planned'},
	{titulo:'Review Scheduled'},
	{titulo:'Review Performed'},
	{titulo:'Review Postponed'},
	{titulo:'Review Suspended'},
	{titulo:'Review Cancelled'},
	{titulo:'Review Aborted'},
	{titulo:'Reason'},
	{titulo:'Description'},
	{titulo:'Review Completed'},
	{titulo:'Tree'},
	{titulo:'Start Date/Time'},
	{titulo:'Review Re-scheduled'},
	{titulo:'Screening Activity'},
	{titulo:'Screening planned'},
	{titulo:'Screening scheduled'},
	{titulo:'Screening performed'},
	{titulo:'Screening activities complete'},
	{titulo:'Screening abandoned'},
	{titulo:'Screening postponed'},
	{titulo:'Screening cancelled'},
	{titulo:'Screening suspended'},
	{titulo:'Description'},
	{titulo:'Service type'},
	{titulo:'Tree'},
	{titulo:'Requestor identifier'},
	{titulo:'Requestor'},
	{titulo:'Receiver identifier'},
	{titulo:'Receiver'},
	{titulo:'Screening expired'},
	{titulo:'Screening incomplete'},
	{titulo:'Screening Date/Time'},
	{titulo:'Tree'},
	{titulo:'Activity Name'},
	{titulo:'Reason'},
	{titulo:'Screening rescheduled'},
	{titulo:'Screening declined'},
	{titulo:'Comment'},
	{titulo:'Service'},
	{titulo:'Tree'},
	{titulo:'Service planned'},
	{titulo:'Service scheduled'},
	{titulo:'Service delivered'},
	{titulo:'Service activity complete'},
	{titulo:'Service abandoned'},
	{titulo:'Service postponed'},
	{titulo:'Service cancelled'},
	{titulo:'Service suspended'},
	{titulo:'Service name'},
	{titulo:'Reason'},
	{titulo:'Description'},
	{titulo:'Service type'},
	{titulo:'Tree'},
	{titulo:'Requestor identifier'},
	{titulo:'Requestor'},
	{titulo:'Receiver identifier'},
	{titulo:'Receiver'},
	{titulo:'Sequence'},
	{titulo:'Service expired'},
	{titulo:'Scheduled date/time'},
	{titulo:'Service request sent'},
	{titulo:'Service detail'},
	{titulo:'Comment'},
	{titulo:'Multimedia'},
	{titulo:'Transfusion'},
	{titulo:'Tree'},
	{titulo:'Planned'},
	{titulo:'Blood products ordered'},
	{titulo:'Prepared (Matching)'},
	{titulo:'Postponed'},
	{titulo:'Cancelled'},
	{titulo:'Blood and patient identification checked'},
	{titulo:'Transfusion unit commenced'},
	{titulo:'Transfusion suspended'},
	{titulo:'Transfusion stopped'},
	{titulo:'Transfusion has been completed'},
	{titulo:'Consent obtained'},
	{titulo:'Transfusion unit completed'},
	{titulo:'Type of blood unit'},
	{titulo:'Sequence number'},
	{titulo:'Proportion administered'},
	{titulo:'Reason'},
	{titulo:'Country of origin of blood product'},
	{titulo:'Clinical description'},
	{titulo:'Reaction details'},
	{titulo:'Related records'},
	{titulo:'Administration details'},
	{titulo:'Patient admission'},
	{titulo:'Tree'},
	{titulo:'Patient class'},
	{titulo:'Inpatient/overnight patient'},
	{titulo:'Same day patient'},
	{titulo:'Outpatient'},
	{titulo:'Emergency patient'},
	{titulo:'Community client'},
	{titulo:'Pre-admit'},
	{titulo:'Commercial account'},
	{titulo:'Not-applicable'},
	{titulo:'Unknown'},
	{titulo:'Admission type'},
	{titulo:'Accident'},
	{titulo:'Emergency'},
	{titulo:'Labour & Delivery'},
	{titulo:'Routine'},
	{titulo:'Newborn'},
	{titulo:'Urgent'},
	{titulo:'Elective'},
	{titulo:'Geriatric respite admission'},
	{titulo:'Statistical admission'},
	{titulo:'Pre-admit number'},
	{titulo:'Referring doctor'},
	{titulo:'Hospital service'},
	{titulo:'Admit source'},
	{titulo:'Admitting doctor'},
	{titulo:'Financial class'},
	{titulo:'Australian Health Care Agreements'},
	{titulo:'Private health insurance'},
	{titulo:'Self-funded'},
	{titulo:'Workers compensation'},
	{titulo:'Charge price indicator'},
	{titulo:'Admit date/time'},
	{titulo:'Assigned patient location'},
	{titulo:'Point of care/Unit'},
	{titulo:'Ward'},
	{titulo:'Room'},
	{titulo:'Bed'},
	{titulo:'Location type'},
	{titulo:'Clinic'},
	{titulo:'Address'},
	{titulo:'Street'},
	{titulo:'City'},
	{titulo:'State/province'},
	{titulo:'Post code'},
	{titulo:'Country'},
	{titulo:'Home'},
	{titulo:'Department'},
	{titulo:'Nursing unit'},
	{titulo:'Providers office'},
	{titulo:'Prior patient location'},
	{titulo:'Adress'},
	{titulo:'Attending doctor'},
	{titulo:'ID'},
	{titulo:'Family name'},
	{titulo:'Building'},
	{titulo:'Floor'},
	{titulo:'Location description'},
	{titulo:'Facility'},
	{titulo:'Namespace ID'},
	{titulo:'Universal ID'},
	{titulo:'Universal ID type'},
	{titulo:'DNS'},
	{titulo:'GUID'},
	{titulo:'HCD'},
	{titulo:'HL7'},
	{titulo:'ISO'},
	{titulo:'L, M, N'},
	{titulo:'Random'},
	{titulo:'UUID'},
	{titulo:'x400'},
	{titulo:'x500'},
	{titulo:'Facility'},
	{titulo:'Last name'},
	{titulo:'Consulting doctor'},
	{titulo:'Motor vehicle third party personal claim'},
	{titulo:'Other compensation (e.g. public liability, common law, medical negligence)'},
	{titulo:'Department of Veterans Affairs'},
	{titulo:'Department of Defence'},
	{titulo:'Correctional facility'},
	{titulo:'Other hospital or public authority (contracted care)'},
	{titulo:'Reciprocal health care agreements (with other countries)'},
	{titulo:'Other'},
	{titulo:'Not known'},
	{titulo:'Arrival'},
	{titulo:'Item tree'},
	{titulo:'Arrival mode'},
	{titulo:'Entry mode'},
	{titulo:'Referral source'},
	{titulo:'Discharge summary'},
	{titulo:'Tree'},
	{titulo:'Clinical condition of the patient'},
	{titulo:'Cured'},
	{titulo:'Improved'},
	{titulo:'Same state'},
	{titulo:'Worse'},
	{titulo:'Deceased'},
	{titulo:'Undetermined.'},
	{titulo:'Discharge date/time'},
	{titulo:'Last patient location'},
	{titulo:'Point of care/Unit'},
	{titulo:'Ward'},
	{titulo:'Room'},
	{titulo:'Bed'},
	{titulo:'Facility'},
	{titulo:'Universal ID type'},
	{titulo:'Universal ID'},
	{titulo:'Namespace ID'},
	{titulo:'Building'},
	{titulo:'Floor'},
	{titulo:'Location description'},
	{titulo:'Location type'},
	{titulo:'Address'},
	{titulo:'Country'},
	{titulo:'Post code'},
	{titulo:'State/Province'},
	{titulo:'City'},
	{titulo:'Street'},
	{titulo:'Discharge doctor'},
	{titulo:'ID'},
	{titulo:'Family name'},
	{titulo:'Last name'},
	{titulo:'Lenght of stay'},
	{titulo:'Final price charge indicator'},
	{titulo:'Discharge status'},
	{titulo:'Discharge home'},
	{titulo:'Discharge to another hospital'},
	{titulo:'Discharge to skilled nursing facility'},
	{titulo:'Discharge to intermediate care facility'},
	{titulo:'Discharge home health care organization'},
	{titulo:'Left against advice'},
	{titulo:'Transfer to chronic or rehabilitation hospital.'},
	{titulo:'Discharge to mental health  setting.'},
	{titulo:'Discharge at patient´s request'},
	{titulo:'Additional information'},
	{titulo:'Discharge instructions'},
	{titulo:'Transfer to another service'},
	{titulo:'Clinic'},
	{titulo:'Home'},
	{titulo:'Departament'},
	{titulo:'Nursing unit'},
	{titulo:'Provider´s office'},
	{titulo:'Attending doctor'},
	{titulo:'ID'},
	{titulo:'Family name'},
	{titulo:'Last name'},
	{titulo:'Referring doctor'},
	{titulo:'Last name'},
	{titulo:'Family name'},
	{titulo:'ID'},
	{titulo:'Legal constraint'},
	{titulo:'Tree'},
	{titulo:'Type of constraint/order'},
	{titulo:'Start Date'},
	{titulo:'Expiry Date'},
	{titulo:'Description'},
	{titulo:'Nominated party'},
	{titulo:'Nominated party details'},
	{titulo:'Extension'},
	{titulo:'Efficiency of healthcare procedure'},
	{titulo:'Tree'},
	{titulo:'Procedure type'},
	{titulo:'Duration'},
	{titulo:'Quantity expent'},
	{titulo:'Resource usage'},
	{titulo:'Personnel type'},
	{titulo:'Fungible/Medication'},
	{titulo:'Resource type'},
	{titulo:'Fixed assets'},
	{titulo:'Human'},
	{titulo:'Staff quantity'},
	{titulo:'Start date'},
	{titulo:'Specific details'},
	{titulo:'Description'},
	{titulo:'Translation requirement'},
	{titulo:'Tree'},
	{titulo:'Administrative language'},
	{titulo:'Translation required?'},
	{titulo:'Comment'},
	{titulo:'Triage'},
	{titulo:'Tree'},
	{titulo:'Priority assignment'},
	{titulo:'Rationale'},
	{titulo:'Disposition'},
	{titulo:'Absence of information'},
	{titulo:'Tree'},
	{titulo:'Absence statement'},
	{titulo:'Tree'},
	{titulo:'Last updated'},
	{titulo:'Reason for absence'},
	{titulo:'Extension'},
	{titulo:'Advance decision to refuse treatment'},
	{titulo:'Tree'},
	{titulo:'Date of decision'},
	{titulo:'Decision status'},
	{titulo:'Advanced decision to refuse treatment signed'},
	{titulo:'Has advance decision to refuse treatment (Mental Capacity Act 2005)'},
	{titulo:'Tree'},
	{titulo:'Location of advance directive documentation'},
	{titulo:'Informal carer awareness of decision'},
	{titulo:'Discussion with healthcare professional'},
	{titulo:'Comment'},
	{titulo:'Has advance decision to refuse life sustaining treatment (Mental Capacity Act 2005)'},
	{titulo:'Informal carer not aware of advanced directive'},
	{titulo:'Informal carer aware of advanced directive'},
	{titulo:'Decision to refuse treatment discussed with healthcare professional'},
	{titulo:'Advanced directive not signed'},
	{titulo:'Adverse reaction risk'},
	{titulo:'Tree'},
	{titulo:'Substance'},
	{titulo:'Comment'},
	{titulo:'Reaction event'},
	{titulo:'Specific substance'},
	{titulo:'Manifestation'},
	{titulo:'Reaction description'},
	{titulo:'Exposure description'},
	{titulo:'Initial exposure'},
	{titulo:'Certainty'},
	{titulo:'Likely'},
	{titulo:'Duration of exposure'},
	{titulo:'Onset of reaction'},
	{titulo:'Duration of reaction'},
	{titulo:'Reaction details'},
	{titulo:'Reaction comment'},
	{titulo:'Clinical management description'},
	{titulo:'Reporting details'},
	{titulo:'Tree'},
	{titulo:'Reaction reported?'},
	{titulo:'Adverse reaction report'},
	{titulo:'Supporting clinical record information'},
	{titulo:'Report comment'},
	{titulo:'Reaction mechanism'},
	{titulo:'Immune mediated'},
	{titulo:'Non-immune mediated'},
	{titulo:'Last updated'},
	{titulo:'Status'},
	{titulo:'Likely'},
	{titulo:'Confirmed'},
	{titulo:'Refuted'},
	{titulo:'Resolved'},
	{titulo:'Severity of reaction'},
	{titulo:'Severe'},
	{titulo:'Moderate'},
	{titulo:'Mild'},
	{titulo:'Suspected'},
	{titulo:'Exposure details'},
	{titulo:'Report summary'},
	{titulo:'Criticality'},
	{titulo:'Low'},
	{titulo:'High'},
	{titulo:'Route of exposure'},
	{titulo:'Information source'},
	{titulo:'Onset of last reaction'},
	{titulo:'Confirmed'},
	{titulo:'Clinical management details'},
	{titulo:'Category'},
	{titulo:'Food'},
	{titulo:'Medication'},
	{titulo:'Other'},
	{titulo:'Indeterminate'},
	{titulo:'Date of report'},
	{titulo:'Indeterminate'},
	{titulo:'Suspected'},
	{titulo:'Extension'},
	{titulo:'Alcohol consumption summary'},
	{titulo:'Tree'},
	{titulo:'Current drinker'},
	{titulo:'Former drinker'},
	{titulo:'Lifetime non-drinker'},
	{titulo:'Episode start date'},
	{titulo:'Quit date'},
	{titulo:'Regular consumption commenced'},
	{titulo:'Overall quit date'},
	{titulo:'Overall comment'},
	{titulo:'Tree'},
	{titulo:'Last updated'},
	{titulo:'Typical consumption (alcohol units)'},
	{titulo:'Number of quit attempts'},
	{titulo:'Episode details'},
	{titulo:'Per type'},
	{titulo:'Pattern'},
	{titulo:'Overall description'},
	{titulo:'Status'},
	{titulo:'Description'},
	{titulo:'Current drinker'},
	{titulo:'Per episode'},
	{titulo:'Comment'},
	{titulo:'Quit date definition'},
	{titulo:'Extension'},
	{titulo:'Current drinker definition'},
	{titulo:'Former drinker definition'},
	{titulo:'Type details'},
	{titulo:'Lifetime non-drinker definition'},
	{titulo:'Daily consumption commenced'},
	{titulo:'Episode label'},
	{titulo:'Episode end date'},
	{titulo:'Daily'},
	{titulo:'Non-daily'},
	{titulo:'Quit attempt definition'},
	{titulo:'Overall details'},
	{titulo:'Episode comment'},
	{titulo:'Overall status'},
	{titulo:'Non-drinker'},
	{titulo:'Binge drinking frequency'},
	{titulo:'Alcohol unit definition (mass)'},
	{titulo:'Type'},
	{titulo:'Alcohol free days'},
	{titulo:'Typical consumption (alcohol units)'},
	{titulo:'Episode description'},
	{titulo:'Binge drinking description'},
	{titulo:'Date first intoxicated'},
	{titulo:'Beer'},
	{titulo:'Wine'},
	{titulo:'Cider'},
	{titulo:'Mead'},
	{titulo:'Pulque'},
	{titulo:'Spirits'},
	{titulo:'Fortified wine'},
	{titulo:'Alcohol test'},
	{titulo:'Item tree'},
	{titulo:'Do you drink?'},
	{titulo:'Yes'},
	{titulo:'No'},
	{titulo:'Type of alcohol'},
	{titulo:'Beer'},
	{titulo:'Wine'},
	{titulo:'Spirits'},
	{titulo:'Duration of drinking'},
	{titulo:'Contenxt'},
	{titulo:'Social'},
	{titulo:'Alone'},
	{titulo:'Occasional'},
	{titulo:'Frequency'},
	{titulo:'Once a day'},
	{titulo:'Once a week'},
	{titulo:'Weekends'},
	{titulo:'With/without dinner'},
	{titulo:'Item tree'},
	{titulo:'Date last updated'},
	{titulo:'Citation'},
	{titulo:'Tree'},
	{titulo:'Citation content'},
	{titulo:'Clinical Synopsis'},
	{titulo:'List'},
	{titulo:'Synopsis'},
	{titulo:'Tree'},
	{titulo:'Extension'},
	{titulo:'Communication capability'},
	{titulo:'ItemTree'},
	{titulo:'Description'},
	{titulo:'Language'},
	{titulo:'Additional details'},
	{titulo:'Overall comment'},
	{titulo:'ItemTree'},
	{titulo:'Extension'},
	{titulo:'Last updated'},
	{titulo:'Per language'},
	{titulo:'Capability details'},
	{titulo:'Preferred language'},
	{titulo:'Alternative language'},
	{titulo:'Comment'},
	{titulo:'Communication aid'},
	{titulo:'Consumer note'},
	{titulo:'Tree'},
	{titulo:'Topic name'},
	{titulo:'Note'},
	{titulo:'Date'},
	{titulo:'Container'},
	{titulo:'Tree'},
	{titulo:'Detail'},
	{titulo:'Contraceptive summary'},
	{titulo:'Tree'},
	{titulo:'Current user'},
	{titulo:'Former user'},
	{titulo:'Never used'},
	{titulo:'Episode start date'},
	{titulo:'End date'},
	{titulo:'Regular contraception commenced'},
	{titulo:'Overall end date'},
	{titulo:'Start date'},
	{titulo:'Overall comment'},
	{titulo:'Tree'},
	{titulo:'Last updated'},
	{titulo:'Contraception'},
	{titulo:'Intent'},
	{titulo:'Episode details'},
	{titulo:'Per type'},
	{titulo:'Description'},
	{titulo:'Overall description'},
	{titulo:'Status'},
	{titulo:'Description'},
	{titulo:'None'},
	{titulo:'Combination pill'},
	{titulo:'Progestogen-only pill'},
	{titulo:'Male sterilisation'},
	{titulo:'Former user'},
	{titulo:'Current user'},
	{titulo:'Female condom'},
	{titulo:'Per episode'},
	{titulo:'Clinical indication'},
	{titulo:'Female sterilisation'},
	{titulo:'Comment'},
	{titulo:'Extension'},
	{titulo:'Reason for cessation'},
	{titulo:'Current user definition'},
	{titulo:'Former user definition'},
	{titulo:'Type details'},
	{titulo:'Male condom'},
	{titulo:'Never used definition'},
	{titulo:'Episode label'},
	{titulo:'Episode end date'},
	{titulo:'Overall details'},
	{titulo:'Episode comment'},
	{titulo:'IUD'},
	{titulo:'Overall status'},
	{titulo:'Never used'},
	{titulo:'Hormone implant'},
	{titulo:'Diaphragm'},
	{titulo:'Depot progestogen injection'},
	{titulo:'Withdrawal'},
	{titulo:'Fertility awareness'},
	{titulo:'Abstinence'},
	{titulo:'Reaction to anti-VEGF'},
	{titulo:'No response to treatment'},
	{titulo:'Morphologic deterioration'},
	{titulo:'Intravitreal anti-VEGF'},
	{titulo:'Very low VA'},
	{titulo:'Healed lesions'},
	{titulo:'Multimorbidity'},
	{titulo:'Contraindication'},
	{titulo:'Contraindication of intravitreal anti-VEGF injections'},
	{titulo:'Tree'},
	{titulo:'Contraindication'},
	{titulo:'Contraindication'},
	{titulo:'Evidence/Rationale'},
	{titulo:'Evidence/Rationale'},
	{titulo:'Date Last Updated'},
	{titulo:'Tree'},
	{titulo:'Contraindication'},
	{titulo:'Tree'},
	{titulo:'Contraindicated intervention'},
	{titulo:'Rationale'},
	{titulo:'Last updated'},
	{titulo:'Tree'},
	{titulo:'Criticality'},
	{titulo:'Comment'},
	{titulo:'Review date'},
	{titulo:'Low'},
	{titulo:'High'},
	{titulo:'Indeterminate'},
	{titulo:'Category'},
	{titulo:'Status'},
	{titulo:'Suspected'},
	{titulo:'Likely'},
	{titulo:'Confirmed'},
	{titulo:'Resolved'},
	{titulo:'Refuted'},
	{titulo:'Extension'},
	{titulo:'Clinical indication'},
	{titulo:'Valid period start'},
	{titulo:'Medical device summary'},
	{titulo:'Tree'},
	{titulo:'Status'},
	{titulo:'Never'},
	{titulo:'Current'},
	{titulo:'Previous'},
	{titulo:'Device name'},
	{titulo:'Start date'},
	{titulo:'End date'},
	{titulo:'Structured detail'},
	{titulo:'Body site'},
	{titulo:'Structured body site'},
	{titulo:'Description'},
	{titulo:'Description'},
	{titulo:'Tree'},
	{titulo:'Last updated'},
	{titulo:'Extension'},
	{titulo:'Next review due'},
	{titulo:'Device type'},
	{titulo:'Multimedia'},
	{titulo:'Device details'},
	{titulo:'URI to original data'},
	{titulo:'Differential diagnoses'},
	{titulo:'Tree'},
	{titulo:'Differential'},
	{titulo:'Likelihood'},
	{titulo:'Comment'},
	{titulo:'Rationale'},
	{titulo:'Diagnosis'},
	{titulo:'List'},
	{titulo:'Reference'},
	{titulo:'Suspected'},
	{titulo:'Likely'},
	{titulo:'DR screening convenient'},
	{titulo:'Arbol'},
	{titulo:'Exclusion statement'},
	{titulo:'Arbol'},
	{titulo:'Date last decision'},
	{titulo:'Admittance in screening'},
	{titulo:'Screening compliant'},
	{titulo:'Screening not necessary'},
	{titulo:'Excluded from Screening'},
	{titulo:'Blind'},
	{titulo:'Deceased'},
	{titulo:'Learning disability'},
	{titulo:'Moved away'},
	{titulo:'No current contact details'},
	{titulo:'No longer diabetic'},
	{titulo:'Physical disorder'},
	{titulo:'Terminal illness'},
	{titulo:'Under care of ophthalmologist'},
	{titulo:'Other'},
	{titulo:'Comment'},
	{titulo:'Education summary'},
	{titulo:'Tree'},
	{titulo:'Highest level completed'},
	{titulo:'Age commenced'},
	{titulo:'Comment'},
	{titulo:'Description'},
	{titulo:'Tree'},
	{titulo:'Extension'},
	{titulo:'Last updated'},
	{titulo:'Education record'},
	{titulo:'Additional details'},
	{titulo:'Age ceased'},
	{titulo:'Special education needs'},
	{titulo:'Exclusion - global'},
	{titulo:'Tree'},
	{titulo:'Global exclusion statement'},
	{titulo:'Global exclusion of problems/diagnoses'},
	{titulo:'Global exclusion of family history'},
	{titulo:'Global exclusion of medication use'},
	{titulo:'Global exclusion of procedures'},
	{titulo:'Global exclusion of adverse reactions'},
	{titulo:'Tree'},
	{titulo:'Extension'},
	{titulo:'Comment'},
	{titulo:'Exclusion - specific'},
	{titulo:'Tree'},
	{titulo:'Exclusion statement'},
	{titulo:'Excluded concept'},
	{titulo:'Problem/diagnosis'},
	{titulo:'Family problem/diagnosis'},
	{titulo:'Medication'},
	{titulo:'Procedure'},
	{titulo:'Adverse reaction substance'},
	{titulo:'Tree'},
	{titulo:'Extension'},
	{titulo:'Comment'},
	{titulo:'Exposure'},
	{titulo:'Tree'},
	{titulo:'Agent'},
	{titulo:'Overall Description'},
	{titulo:'Ongoing Exposure'},
	{titulo:'Category'},
	{titulo:'Environmental'},
	{titulo:'Occupational'},
	{titulo:'Tree'},
	{titulo:'Date Updated'},
	{titulo:'Exposure Details'},
	{titulo:'Date of Onset'},
	{titulo:'Date Ceased'},
	{titulo:'Description'},
	{titulo:'Family history'},
	{titulo:'Tree'},
	{titulo:'Summary'},
	{titulo:'Per family member'},
	{titulo:'Family member name'},
	{titulo:'Date of birth'},
	{titulo:'Clinical history'},
	{titulo:'Problem/diagnosis name'},
	{titulo:'Age at onset'},
	{titulo:'Age at death'},
	{titulo:'Clinical description'},
	{titulo:'Cause of death?'},
	{titulo:'Relationship'},
	{titulo:'Alias'},
	{titulo:'Biomarker description'},
	{titulo:'Deceased?'},
	{titulo:'Biomarkers'},
	{titulo:'Tree'},
	{titulo:'Last Updated'},
	{titulo:'Biomarker details'},
	{titulo:'Per problem'},
	{titulo:'Problem/diagnosis name'},
	{titulo:'Description'},
	{titulo:'Extension'},
	{titulo:'Comment'},
	{titulo:'Family member details'},
	{titulo:'Multimedia'},
	{titulo:'Date of death'},
	{titulo:'Problem details'},
	{titulo:'Biological sex'},
	{titulo:'Direct cause or closely related'},
	{titulo:'Unrelated'},
	{titulo:'Indeterminate'},
	{titulo:'Gender'},
	{titulo:'Gender identity'},
	{titulo:'Tree'},
	{titulo:'Tree'},
	{titulo:'Last updated'},
	{titulo:'Extension'},
	{titulo:'Comment'},
	{titulo:'Sex assigned at birth'},
	{titulo:'Preferred pronoun'},
	{titulo:'Administrative gender'},
	{titulo:'Additional details'},
	{titulo:'Gender expression'},
	{titulo:'Legal gender'},
	{titulo:'Goal'},
	{titulo:'Tree'},
	{titulo:'Goal name'},
	{titulo:'Goal proposed date'},
	{titulo:'Goal end date'},
	{titulo:'Target'},
	{titulo:'Target path'},
	{titulo:'Target'},
	{titulo:'Target proposed date'},
	{titulo:'Target end date'},
	{titulo:'Clinical indication'},
	{titulo:'Target name'},
	{titulo:'Goal description'},
	{titulo:'Goal outcome'},
	{titulo:'Achieved'},
	{titulo:'Partially achieved'},
	{titulo:'Not achieved'},
	{titulo:'Target outcome'},
	{titulo:'Achieved'},
	{titulo:'Partially achieved'},
	{titulo:'Not achieved'},
	{titulo:'Goal comment'},
	{titulo:'Target comment'},
	{titulo:'Target description'},
	{titulo:'Goal start date'},
	{titulo:'Tree'},
	{titulo:'Extension'},
	{titulo:'Readiness for change'},
	{titulo:'Last updated'},
	{titulo:'Health risk assessment'},
	{titulo:'structure'},
	{titulo:'Health risk'},
	{titulo:'Risk assessment'},
	{titulo:'Rationale'},
	{titulo:'Tree'},
	{titulo:'Extension'},
	{titulo:'Link to evidence'},
	{titulo:'Risk factor'},
	{titulo:'Description'},
	{titulo:'Comment'},
	{titulo:'Risk factors'},
	{titulo:'Presence'},
	{titulo:'Present'},
	{titulo:'Absent'},
	{titulo:'Assessment type'},
	{titulo:'Relative risk'},
	{titulo:'Absolute risk'},
	{titulo:'Time period'},
	{titulo:'Last updated'},
	{titulo:'Assessment method'},
	{titulo:'Indeterminate'},
	{titulo:'Detail'},
	{titulo:'Mitigated'},
	{titulo:'Date identified'},
	{titulo:'Comment'},
	{titulo:'Housing summary'},
	{titulo:'Tree'},
	{titulo:'Description'},
	{titulo:'Additional details'},
	{titulo:'Comment'},
	{titulo:'Housing record'},
	{titulo:'Tree'},
	{titulo:'Last updated'},
	{titulo:'Extension'},
	{titulo:'Immunisation summary'},
	{titulo:'Tree'},
	{titulo:'Infectious disease or agent'},
	{titulo:'Primary course status'},
	{titulo:'Not commenced'},
	{titulo:'Incomplete'},
	{titulo:'Complete'},
	{titulo:'Indeterminate'},
	{titulo:'Date primary course completed'},
	{titulo:'Date of last booster'},
	{titulo:'Immunisation status'},
	{titulo:'Immunisation up-to-date'},
	{titulo:'Immunisation not up-to-date'},
	{titulo:'Tree'},
	{titulo:'Next review due'},
	{titulo:'Last updated'},
	{titulo:'Comment'},
	{titulo:'Infant Feeding Summary'},
	{titulo:'Tree'},
	{titulo:'Description'},
	{titulo:'Feeding'},
	{titulo:'Age Commenced'},
	{titulo:'Age Ceased'},
	{titulo:'Type'},
	{titulo:'Total Duration of Breast Feeding'},
	{titulo:'Age Commenced Solid Foods'},
	{titulo:'Comment'},
	{titulo:'Age Weaned'},
	{titulo:'Predominantly Breastfed'},
	{titulo:'Predominantly Formula'},
	{titulo:'Mixed'},
	{titulo:'Infectious Disease Summary'},
	{titulo:'Tree'},
	{titulo:'Infectious Disease'},
	{titulo:'Immune Status'},
	{titulo:'Comment'},
	{titulo:'Tree'},
	{titulo:'Date of Last Updated'},
	{titulo:'Description of Immune Status'},
	{titulo:'Evidence'},
	{titulo:'Previous Infection?'},
	{titulo:'Confirmed'},
	{titulo:'Suspected'},
	{titulo:'No Evidence'},
	{titulo:'Very low VA'},
	{titulo:'Healed lesions'},
	{titulo:'Multimorbidity'},
	{titulo:'Reaction to anti-VEGF'},
	{titulo:'VA decrease'},
	{titulo:'Morphologic deterioration'},
	{titulo:'Enrollment in a long-term healthcare process'},
	{titulo:'Enrollment in intravitreal anti-VEGF therapy for wet AMD'},
	{titulo:'Tree'},
	{titulo:'Tree'},
	{titulo:'Date decision'},
	{titulo:'Healthcare process'},
	{titulo:'Description'},
	{titulo:'Criteria'},
	{titulo:'Criteria'},
	{titulo:'Decision review'},
	{titulo:'Admittance'},
	{titulo:'Enrollment in a long-term healthcare process'},
	{titulo:'Tree'},
	{titulo:'Tree'},
	{titulo:'Date decision'},
	{titulo:'Healthcare process'},
	{titulo:'Description'},
	{titulo:'Criteria'},
	{titulo:'Decision review'},
	{titulo:'Admittance'},
	{titulo:'Medication safety event'},
	{titulo:'Tree'},
	{titulo:'Safety event type'},
	{titulo:'MEDRA classification'},
	{titulo:'DateTime of event onset'},
	{titulo:'Intervention'},
	{titulo:'Intervention result'},
	{titulo:'Adverse effect'},
	{titulo:'Related trigger'},
	{titulo:'Reaction'},
	{titulo:'Liklihood of causation'},
	{titulo:'Description of event'},
	{titulo:'Actual patient outcome'},
	{titulo:'Patient outcome category'},
	{titulo:'[A] Circumstances or events that have the capacity to cause error'},
	{titulo:'[B] An error that did not reach the patient'},
	{titulo:'[C] An error that reached the patient but did not cause harm'},
	{titulo:'[D] An error that reache the patient and reqired monitoring or intervention to confirm that it resulted in no harm to the patient'},
	{titulo:'[E] Temporary harm to the patient and required intervention'},
	{titulo:'[F] Temporary harm to the patient and required initial or prolonged hospitalization'},
	{titulo:'[G] Permanent patient harm'},
	{titulo:'[H] Intervention required to sustain life'},
	{titulo:'[I] Patient death'},
	{titulo:'Estimated cause of event'},
	{titulo:'Clinical'},
	{titulo:'Personal'},
	{titulo:'Economic'},
	{titulo:'Verbal miscommunication'},
	{titulo:'Written miscomunication-Illegible handwritting'},
	{titulo:'Written miscomunication-Abbreviations'},
	{titulo:'Written miscomunication-Non metric units of measurement'},
	{titulo:'Written miscomunication-Decimal point'},
	{titulo:'Misread or didnt read'},
	{titulo:'Misinterpretation of the order'},
	{titulo:'Sound-alike drug name'},
	{titulo:'Look-alike drug name'},
	{titulo:'Packaging-Inappropriate Packaging or Design'},
	{titulo:'Packing-Dosage form'},
	{titulo:'Packaging-Error due to similarity to another drug (colour, form, size)'},
	{titulo:'Packaging-Error due different strength'},
	{titulo:'Human factors-Lack of information/knowledge'},
	{titulo:'Work not accomplished'},
	{titulo:'Incomplete documentation'},
	{titulo:'Work overload, burn out syndrome'},
	{titulo:'Fatigue/Lack of sleep'},
	{titulo:'Confrontational or intimidating behaviour'},
	{titulo:'Inappropriate lighting'},
	{titulo:'Inappropriate temperature/humidity'},
	{titulo:'Frequent interuptions and distractions'},
	{titulo:'Lack of staff'},
	{titulo:'Other'},
	{titulo:'DateTime of reaction onset'},
	{titulo:'Severity'},
	{titulo:'Low'},
	{titulo:'Medium'},
	{titulo:'High'},
	{titulo:'Potential patient outcome'},
	{titulo:'Additional comment'},
	{titulo:'Cause of event'},
	{titulo:'Comment'},
	{titulo:'Main event for case?'},
	{titulo:'Intervention details'},
	{titulo:'Summary details'},
	{titulo:'Admission diagnosis classification'},
	{titulo:'Discharge diagnosis classification'},
	{titulo:'TNM classification'},
	{titulo:'Oncological case details'},
	{titulo:'Order of treatment'},
	{titulo:'Reason for case closure'},
	{titulo:'Effectiveness of therapy'},
	{titulo:'Completely effective'},
	{titulo:'Partially effective'},
	{titulo:'Disease status unchanged'},
	{titulo:'Ineffective - disease progressing unchecked.'},
	{titulo:'Link to main event'},
	{titulo:'Treatment complete'},
	{titulo:'Treatment aborted'},
	{titulo:'Reason treatment aborted'},
	{titulo:'Transfusion of Blood or Use of Blood Products'},
	{titulo:'Acute Dialysis'},
	{titulo:'Positive Blood Culture'},
	{titulo:'X-Ray or Doppler Studies for Emboli or Deep Vein Thrombosis'},
	{titulo:'Decrease in Hemoglobin or Hematocrit of 25% or Greater'},
	{titulo:'Patient Fall'},
	{titulo:'Pressure Ulcers'},
	{titulo:'Readmission within 30 Days'},
	{titulo:'Restraint Use'},
	{titulo:'Healthcare-Associated Infections'},
	{titulo:'In-Hospital Stroke'},
	{titulo:'Clostridium difficile Positive Stool'},
	{titulo:'Partial Thromboplastin Time (PTT) Greater than 100 Seconds'},
	{titulo:'International Normalized Ratio (INR) Greater than 6'},
	{titulo:'Glucose Less than 50 mg/dl'},
	{titulo:'Rising BUN or Serum Creatinine Two Times (2x) over Baseline'},
	{titulo:'Vitamin K Administration'},
	{titulo:'Diphenhydramine (Benadryl) Administration'},
	{titulo:'Romazicon (Flumazenil) Administration'},
	{titulo:'Naloxone (Narcan) Administration'},
	{titulo:'Anti-Emetic Administration'},
	{titulo:'Over-Sedation/Hypotension'},
	{titulo:'Abrupt Medication Stop'},
	{titulo:'Intra- or Post-Operative Death'},
	{titulo:'Mechanical Ventilation Greater than 24 Hours Post-Operatively'},
	{titulo:'Intra-Operative Administration of Epinephrine, Norepinephrine, Naloxone, or Romazicon'},
	{titulo:'Pneumonia Onset'},
	{titulo:'Readmission to the Intensive Care Unit'},
	{titulo:'Terbutaline Use'},
	{titulo:'Platelet Count Less than 50,000'},
	{titulo:'Administration of Oxytocic Agents (such as oxytocin, methylergonovine, and 15-methyl-prostaglandin in the post-partum period)'},
	{titulo:'Administration of General Anesthesia'},
	{titulo:'Readmission to the ED within 48 Hours'},
	{titulo:'Time in ED Greater than 6 Hours'},
	{titulo:'Prescriber informed'},
	{titulo:'Nurse informed/instructed'},
	{titulo:'Dispensing rejected'},
	{titulo:'Drug recalled from the ward'},
	{titulo:'Dietary regime changed'},
	{titulo:'Food supplement discontinued'},
	{titulo:'Food supplement initiated'},
	{titulo:'Reconstitution solvent changed'},
	{titulo:'Diluent changed'},
	{titulo:'Drug changed'},
	{titulo:'Dose increased'},
	{titulo:'Dose decreased'},
	{titulo:'Dosage form changed'},
	{titulo:'Administration interval changed'},
	{titulo:'Drug discontinued'},
	{titulo:'Drug initiated'},
	{titulo:'Drug administration rate changed'},
	{titulo:'Route of administration changed'},
	{titulo:'Resuscitation required'},
	{titulo:'Heamodialysis required'},
	{titulo:'Transplantation required'},
	{titulo:'Transfusion required'},
	{titulo:'Operating procedure required'},
	{titulo:'Additional laboratory test(s) required'},
	{titulo:'Physiotherapy required'},
	{titulo:'Psychotherapy required'},
	{titulo:'Other'},
	{titulo:'Unknown'},
	{titulo:'*Intervencija preprečila, da bi zaplet dosegel pacienta(en)'}
	]
	}
})